// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package io.github.hizhangbo.model;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.hizhangbo.model.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstName = 1;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 1;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 2;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 2;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string emailAddress = 3;</code>
     * @return The emailAddress.
     */
    java.lang.String getEmailAddress();
    /**
     * <code>string emailAddress = 3;</code>
     * @return The bytes for emailAddress.
     */
    com.google.protobuf.ByteString
        getEmailAddressBytes();

    /**
     * <code>string homeAddress = 4;</code>
     * @return The homeAddress.
     */
    java.lang.String getHomeAddress();
    /**
     * <code>string homeAddress = 4;</code>
     * @return The bytes for homeAddress.
     */
    com.google.protobuf.ByteString
        getHomeAddressBytes();

    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return A list containing the skills.
     */
    java.util.List<io.github.hizhangbo.model.UserProto.User.Skill> getSkillsList();
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return The count of skills.
     */
    int getSkillsCount();
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    io.github.hizhangbo.model.UserProto.User.Skill getSkills(int index);
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return A list containing the enum numeric values on the wire for skills.
     */
    java.util.List<java.lang.Integer>
    getSkillsValueList();
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of skills at the given index.
     */
    int getSkillsValue(int index);
  }
  /**
   * Protobuf type {@code io.github.hizhangbo.model.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.hizhangbo.model.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      firstName_ = "";
      lastName_ = "";
      emailAddress_ = "";
      homeAddress_ = "";
      skills_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              emailAddress_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              homeAddress_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skills_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              skills_.add(rawValue);
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  skills_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000001;
                }
                skills_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.hizhangbo.model.UserProto.internal_static_io_github_hizhangbo_model_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.hizhangbo.model.UserProto.internal_static_io_github_hizhangbo_model_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.hizhangbo.model.UserProto.User.class, io.github.hizhangbo.model.UserProto.User.Builder.class);
    }

    /**
     * Protobuf enum {@code io.github.hizhangbo.model.User.Skill}
     */
    public enum Skill
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GOLANG = 0;</code>
       */
      GOLANG(0),
      /**
       * <code>PYTHON = 1;</code>
       */
      PYTHON(1),
      /**
       * <code>JAVA = 2;</code>
       */
      JAVA(2),
      /**
       * <code>RUST = 3;</code>
       */
      RUST(3),
      /**
       * <code>CPP = 4;</code>
       */
      CPP(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GOLANG = 0;</code>
       */
      public static final int GOLANG_VALUE = 0;
      /**
       * <code>PYTHON = 1;</code>
       */
      public static final int PYTHON_VALUE = 1;
      /**
       * <code>JAVA = 2;</code>
       */
      public static final int JAVA_VALUE = 2;
      /**
       * <code>RUST = 3;</code>
       */
      public static final int RUST_VALUE = 3;
      /**
       * <code>CPP = 4;</code>
       */
      public static final int CPP_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Skill valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Skill forNumber(int value) {
        switch (value) {
          case 0: return GOLANG;
          case 1: return PYTHON;
          case 2: return JAVA;
          case 3: return RUST;
          case 4: return CPP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Skill>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Skill> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Skill>() {
              public Skill findValueByNumber(int number) {
                return Skill.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.github.hizhangbo.model.UserProto.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Skill[] VALUES = values();

      public static Skill valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Skill(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.github.hizhangbo.model.User.Skill)
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 1;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 2;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object emailAddress_;
    /**
     * <code>string emailAddress = 3;</code>
     * @return The emailAddress.
     */
    @java.lang.Override
    public java.lang.String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string emailAddress = 3;</code>
     * @return The bytes for emailAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOMEADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object homeAddress_;
    /**
     * <code>string homeAddress = 4;</code>
     * @return The homeAddress.
     */
    @java.lang.Override
    public java.lang.String getHomeAddress() {
      java.lang.Object ref = homeAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string homeAddress = 4;</code>
     * @return The bytes for homeAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHomeAddressBytes() {
      java.lang.Object ref = homeAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILLS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> skills_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, io.github.hizhangbo.model.UserProto.User.Skill> skills_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, io.github.hizhangbo.model.UserProto.User.Skill>() {
              public io.github.hizhangbo.model.UserProto.User.Skill convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                io.github.hizhangbo.model.UserProto.User.Skill result = io.github.hizhangbo.model.UserProto.User.Skill.valueOf(from);
                return result == null ? io.github.hizhangbo.model.UserProto.User.Skill.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return A list containing the skills.
     */
    @java.lang.Override
    public java.util.List<io.github.hizhangbo.model.UserProto.User.Skill> getSkillsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, io.github.hizhangbo.model.UserProto.User.Skill>(skills_, skills_converter_);
    }
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return The count of skills.
     */
    @java.lang.Override
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    @java.lang.Override
    public io.github.hizhangbo.model.UserProto.User.Skill getSkills(int index) {
      return skills_converter_.convert(skills_.get(index));
    }
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @return A list containing the enum numeric values on the wire for skills.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getSkillsValueList() {
      return skills_;
    }
    /**
     * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of skills at the given index.
     */
    @java.lang.Override
    public int getSkillsValue(int index) {
      return skills_.get(index);
    }
    private int skillsMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (!getEmailAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emailAddress_);
      }
      if (!getHomeAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, homeAddress_);
      }
      if (getSkillsList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(skillsMemoizedSerializedSize);
      }
      for (int i = 0; i < skills_.size(); i++) {
        output.writeEnumNoTag(skills_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (!getEmailAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emailAddress_);
      }
      if (!getHomeAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, homeAddress_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(skills_.get(i));
        }
        size += dataSize;
        if (!getSkillsList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }skillsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.hizhangbo.model.UserProto.User)) {
        return super.equals(obj);
      }
      io.github.hizhangbo.model.UserProto.User other = (io.github.hizhangbo.model.UserProto.User) obj;

      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmailAddress()
          .equals(other.getEmailAddress())) return false;
      if (!getHomeAddress()
          .equals(other.getHomeAddress())) return false;
      if (!skills_.equals(other.skills_)) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAILADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getEmailAddress().hashCode();
      hash = (37 * hash) + HOMEADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getHomeAddress().hashCode();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + skills_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.model.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.model.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.hizhangbo.model.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.hizhangbo.model.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.hizhangbo.model.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.hizhangbo.model.User)
        io.github.hizhangbo.model.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.hizhangbo.model.UserProto.internal_static_io_github_hizhangbo_model_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.hizhangbo.model.UserProto.internal_static_io_github_hizhangbo_model_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.hizhangbo.model.UserProto.User.class, io.github.hizhangbo.model.UserProto.User.Builder.class);
      }

      // Construct using io.github.hizhangbo.model.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        emailAddress_ = "";

        homeAddress_ = "";

        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.hizhangbo.model.UserProto.internal_static_io_github_hizhangbo_model_User_descriptor;
      }

      @java.lang.Override
      public io.github.hizhangbo.model.UserProto.User getDefaultInstanceForType() {
        return io.github.hizhangbo.model.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.hizhangbo.model.UserProto.User build() {
        io.github.hizhangbo.model.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.hizhangbo.model.UserProto.User buildPartial() {
        io.github.hizhangbo.model.UserProto.User result = new io.github.hizhangbo.model.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.emailAddress_ = emailAddress_;
        result.homeAddress_ = homeAddress_;
        if (((bitField0_ & 0x00000001) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skills_ = skills_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.hizhangbo.model.UserProto.User) {
          return mergeFrom((io.github.hizhangbo.model.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.hizhangbo.model.UserProto.User other) {
        if (other == io.github.hizhangbo.model.UserProto.User.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getEmailAddress().isEmpty()) {
          emailAddress_ = other.emailAddress_;
          onChanged();
        }
        if (!other.getHomeAddress().isEmpty()) {
          homeAddress_ = other.homeAddress_;
          onChanged();
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.github.hizhangbo.model.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.github.hizhangbo.model.UserProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 1;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 2;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emailAddress_ = "";
      /**
       * <code>string emailAddress = 3;</code>
       * @return The emailAddress.
       */
      public java.lang.String getEmailAddress() {
        java.lang.Object ref = emailAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emailAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emailAddress = 3;</code>
       * @return The bytes for emailAddress.
       */
      public com.google.protobuf.ByteString
          getEmailAddressBytes() {
        java.lang.Object ref = emailAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emailAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emailAddress = 3;</code>
       * @param value The emailAddress to set.
       * @return This builder for chaining.
       */
      public Builder setEmailAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emailAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emailAddress = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailAddress() {
        
        emailAddress_ = getDefaultInstance().getEmailAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string emailAddress = 3;</code>
       * @param value The bytes for emailAddress to set.
       * @return This builder for chaining.
       */
      public Builder setEmailAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emailAddress_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object homeAddress_ = "";
      /**
       * <code>string homeAddress = 4;</code>
       * @return The homeAddress.
       */
      public java.lang.String getHomeAddress() {
        java.lang.Object ref = homeAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          homeAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string homeAddress = 4;</code>
       * @return The bytes for homeAddress.
       */
      public com.google.protobuf.ByteString
          getHomeAddressBytes() {
        java.lang.Object ref = homeAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          homeAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string homeAddress = 4;</code>
       * @param value The homeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setHomeAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        homeAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string homeAddress = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHomeAddress() {
        
        homeAddress_ = getDefaultInstance().getHomeAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string homeAddress = 4;</code>
       * @param value The bytes for homeAddress to set.
       * @return This builder for chaining.
       */
      public Builder setHomeAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        homeAddress_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> skills_ =
        java.util.Collections.emptyList();
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skills_ = new java.util.ArrayList<java.lang.Integer>(skills_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @return A list containing the skills.
       */
      public java.util.List<io.github.hizhangbo.model.UserProto.User.Skill> getSkillsList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, io.github.hizhangbo.model.UserProto.User.Skill>(skills_, skills_converter_);
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @return The count of skills.
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param index The index of the element to return.
       * @return The skills at the given index.
       */
      public io.github.hizhangbo.model.UserProto.User.Skill getSkills(int index) {
        return skills_converter_.convert(skills_.get(index));
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param index The index to set the value at.
       * @param value The skills to set.
       * @return This builder for chaining.
       */
      public Builder setSkills(
          int index, io.github.hizhangbo.model.UserProto.User.Skill value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param value The skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkills(io.github.hizhangbo.model.UserProto.User.Skill value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param values The skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkills(
          java.lang.Iterable<? extends io.github.hizhangbo.model.UserProto.User.Skill> values) {
        ensureSkillsIsMutable();
        for (io.github.hizhangbo.model.UserProto.User.Skill value : values) {
          skills_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkills() {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @return A list containing the enum numeric values on the wire for skills.
       */
      public java.util.List<java.lang.Integer>
      getSkillsValueList() {
        return java.util.Collections.unmodifiableList(skills_);
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of skills at the given index.
       */
      public int getSkillsValue(int index) {
        return skills_.get(index);
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of skills at the given index.
       * @return This builder for chaining.
       */
      public Builder setSkillsValue(
          int index, int value) {
        ensureSkillsIsMutable();
        skills_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param value The enum numeric value on the wire for skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkillsValue(int value) {
        ensureSkillsIsMutable();
        skills_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .io.github.hizhangbo.model.User.Skill skills = 5;</code>
       * @param values The enum numeric values on the wire for skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkillsValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureSkillsIsMutable();
        for (int value : values) {
          skills_.add(value);
        }
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.hizhangbo.model.User)
    }

    // @@protoc_insertion_point(class_scope:io.github.hizhangbo.model.User)
    private static final io.github.hizhangbo.model.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.hizhangbo.model.UserProto.User();
    }

    public static io.github.hizhangbo.model.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.hizhangbo.model.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_hizhangbo_model_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_hizhangbo_model_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\031io.github.hizhangbo.model\"" +
      "\323\001\n\004User\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030" +
      "\002 \001(\t\022\024\n\014emailAddress\030\003 \001(\t\022\023\n\013homeAddre" +
      "ss\030\004 \001(\t\0225\n\006skills\030\005 \003(\0162%.io.github.hiz" +
      "hangbo.model.User.Skill\"<\n\005Skill\022\n\n\006GOLA" +
      "NG\020\000\022\n\n\006PYTHON\020\001\022\010\n\004JAVA\020\002\022\010\n\004RUST\020\003\022\007\n\003" +
      "CPP\020\004R\006PersonB&\n\031io.github.hizhangbo.mod" +
      "elB\tUserProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_hizhangbo_model_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_hizhangbo_model_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_hizhangbo_model_User_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "EmailAddress", "HomeAddress", "Skills", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
